/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursRouteImport } from './routes/cours'
import { Route as ProblemesRouteImport } from './routes/problemes'
import { Route as ProfesseursRouteImport } from './routes/professeurs'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursRoute = CoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemesRoute = ProblemesRouteImport.update({
  id: '/problemes',
  path: '/problemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursRoute = ProfesseursRouteImport.update({
  id: '/professeurs',
  path: '/professeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cours': typeof CoursRoute
  '/problemes': typeof ProblemesRoute
  '/professeurs': typeof ProfesseursRoute
  '/solutions': typeof SolutionsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cours': typeof CoursRoute
  '/problemes': typeof ProblemesRoute
  '/professeurs': typeof ProfesseursRoute
  '/solutions': typeof SolutionsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cours': typeof CoursRoute
  '/problemes': typeof ProblemesRoute
  '/professeurs': typeof ProfesseursRoute
  '/solutions': typeof SolutionsRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cours' | '/problemes' | '/professeurs' | '/solutions' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/cours' | '/problemes' | '/professeurs' | '/solutions' | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/cours'
    | '/problemes'
    | '/professeurs'
    | '/solutions'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursRoute: typeof CoursRoute
  ProblemesRoute: typeof ProblemesRoute
  ProfesseursRoute: typeof ProfesseursRoute
  SolutionsRoute: typeof SolutionsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours': {
      id: '/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof CoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemes': {
      id: '/problemes'
      path: '/problemes'
      fullPath: '/problemes'
      preLoaderRoute: typeof ProblemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs': {
      id: '/professeurs'
      path: '/professeurs'
      fullPath: '/professeurs'
      preLoaderRoute: typeof ProfesseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursRoute: CoursRoute,
  ProblemesRoute: ProblemesRoute,
  ProfesseursRoute: ProfesseursRoute,
  SolutionsRoute: SolutionsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
